---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify Timezone
    command: cat /etc/timezone
    register: timezone_check
  - name: Assert Timezone
    assert:
      that:
        - "{{ timezone_check.stdout }} == {{ zone | default('Etc/UTC') }}"
