---
- name: Converge
  hosts: all
  become: yes

  pre_tasks:
    - name: install ssh
      apt:
        update_cache: true
        name: openssh-server

  tasks:
    - name: "ssh"
      include_role:
        name: "ssh"
