---
galaxy_info:
  role_name: timezone
  author: darsh12
  description: This role changes the timezone according to the tz database

  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - linux
    - timezone

  dependencies:
    - community.general
